name: Release

on:
  release:
    types:
      - published

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: nnqq
          password: ${{ secrets.GH_CI_TOKEN }}
          registry: ghcr.io
          repository: ${{ github.repository }}
          tag_with_ref: true

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_CI_TOKEN }}

      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save k8s

      - name: Update manifest
        run: sed -i 's|busybox|ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}|' $GITHUB_WORKSPACE/deploy/cronjob.yaml

      - name: Apply cron job
        run: kubectl -n infra apply -f ${{ github.workspace }}/deploy
